### ISSUE TITLE
Destroying Surfaces throws error

### ISSUE THREAD

**Issue by feidens** [PEM--/fview-flexgrid#2]
The flexgrid is rendered inside a RenderController yield
```
{{#RenderController id="mainRC" target="content" size="[undefined,undefined]"}}
      {{> yield}}
{{/RenderController}}
```
If the route is changed the surfaces inside the flexgrid get destroyed but the route change is interrupted by the following error:
```
[Log]  debug:  [famous-views]  Destroying Surface (#24) and children (jag_pince.js, line 158)
[Log]  debug:  [famous-views]  Destroying Surface (#25) and children (jag_pince.js, line 158)
[Log]  debug:  [famous-views]  Destroying Surface (#26) and children (jag_pince.js, line 158)
[Error] TypeError: undefined is not an object (evaluating 'this._sequence[i].render')
	commit (pierreeric_fview-flexgrid.js, line 169)
	_applyCommit (mjn_famous.js, line 2579)
	commit (mjn_famous.js, line 2605)
	update (mjn_famous.js, line 402)
	commit (mjn_famous.js, line 1828)
	_applyCommit (mjn_famous.js, line 2579)
	_applyCommit (mjn_famous.js, line 2580)
	_applyCommit (mjn_famous.js, line 2580)
	_applyCommit (mjn_famous.js, line 2580)
	commit (mjn_famous.js, line 2605)
	update (mjn_famous.js, line 402)
	step (mjn_famous.js, line 1024)
	loop (mjn_famous.js, line 1032)
```

**Comment by PEM--** [comment]
Hi @feidens. I've updated the example with **iron:router**: http://fview-flexgrid.meteor.com/.

There is now a button that switch route destroying the content of the **fview-flexgrid**. I don't reproduce your issue.

**Comment by feidens** [comment]
Hi @PEM-- 
I've tested the new example and replaced the items by a Mongo cursor.
This will trigger the error on route change.
A quick fix is to call fetch() on the cursor before using it.

**Comment by PEM--** [comment]
It should be better. Now the `render`method is checked before being called.

Could you tell me if it matches what you were looking at?

**Comment by feidens** [comment]
Sorry for the late answer. Busy week.
A quick test without fetch() shows no error. I think you can close this issue :+1:

**Comment by PEM--** [comment]
Cool.
