### ISSUE TITLE
Scrollview + Flexview: only scrolling on element

### ISSUE THREAD

**Issue by rafaelquintanilha** [PEM--/fview-flexgrid#3]
The architecture of my app is as follows:

I have a HeaderFooterLayout where I render the content:

```
{{>View template="content" target="content" size="[undefined,undefined]" translate="[0,0,-1]"}}
```

And them the content template, who is taking advantage of RenderController and IronRouter:

```
<template name="content">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          {{#Surface class="content" size="[undefined,undefined]"}}{{/Surface}}
          {{#RenderController transition=getTransition id="mainRC"}}
              {{>yield}}
          {{/RenderController}}
        </div>
      </div>
    </div>
</template>
```

When `{{> yeld}}` renders something like that:

```
<template name="addSafristaWrapper">
  {{#Scrollview}}
    {{>Surface template="addSafrista" size="[undefined,true]" class="content"}}
  {{/Scrollview}}
</template>
```

It works perfectly fine and I'm able to scroll on every part of the screen. But when using FlexGrid like that:

```
<template name="listSafristas">
  {{#Scrollview size="[undefined, undefined]" id="scroll"}}
    {{#FlexGrid itemSize="[220,300]"}}
         {{#famousEach safristas}}
           {{>Surface template="cardSafrista"}}
         {{/famousEach}}
    {{/FlexGrid}}
  {{/Scrollview}}
</template>
```

The scroll only works **on** grid elements. So, for example, if the grid is 3x3 and I have 8 elements, that's one spot left and I'm not able to scroll in this empty spot (the same in between the grid elements when they are spare enough).

Any thoughts?

**Comment by PEM--** [comment]
Hi @rafaelquintanilha, why is this an issue on this package? Sounds more like a question to me :confused: 

Your `ScrollView` doesn't receive any scroll events.

You can find an example here: https://github.com/PEM--/fview-flexgrid/blob/master/example/client/main.coffee#L67
